const DB ={
    ASSIGNUSER:'LEAVESTABLE',
    GETUSER:'GETUSERSBYID',
     ADDLEAVESOWNER:'LEAVEPERMISSION',
    ADDLEAVES:'GETUSERBYID',
    APPROVELEAVES:'APPROVELEAVE',
    APPROVELEAVESBYOWNER:'ASSIGNLEAVESBYOWNER',
    GETCHECKUSER:"GETCHECKID"
}
module.exports={
    DB
}